stages:
  - stage: Build
    displayName: 'Build Stage'
    jobs:
      - job: Build
        displayName: 'Build the Function App'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: |
              curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
              sudo apt-get install -y nodejs
            displayName: 'Install Node.js'

          - script: |
              npm install --legacy-peer-deps
            displayName: 'Install Dependencies'

          - script: |
              npm run build
            displayName: 'Run Build Step'

  - stage: Test
    displayName: 'Test Stage'
    jobs:
      - job: Test
        displayName: 'Run Unit Tests'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: |
              npm install --legacy-peer-deps
            displayName: 'Install Dependencies for Test Stage'

          - script: |
              echo "Running tests with verbose output..."
              npx jest --verbose
            displayName: 'Run Tests'

          - script: |
              echo "Checking node_modules..."
              ls -l node_modules/
              echo "Checking installed jest version..."
              npx jest --version
            displayName: 'Verify Installed Dependencies'

  - stage: Deploy
    displayName: 'Deploy to Azure'
    jobs:
      - job: Deploy
        displayName: 'Deploy Function to Azure'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: AzureFunctionApp@1
            inputs:
              azureSubscription: 'leesa9019432'
              appName: 'leesa9019432'
              package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
