stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: Build
    displayName: 'Build the Function App'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: UseNode@2
      inputs:
        versionSpec: '16.x'
        addToPath: true
    - script: |
        npm install
        npm run build
      displayName: 'Build the Azure Function'

- stage: Test
  displayName: 'Test Stage'
  jobs:
  - job: Test
    displayName: 'Run Unit Tests'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        npm test
      displayName: 'Run Tests'

- stage: Deploy
  displayName: 'Deploy to Azure'
  jobs:
  - job: Deploy
    displayName: 'Deploy Function to Azure'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureFunctionApp@1
      inputs:
        azureSubscription: 'leesa9019432'
        appName: 'leesa9019432'
        package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
